[package]
name = "pons"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = "0.11.22"
tokio = { version = "1.34.0", features = ["full"] }
cursive = { git = "https://github.com/gyscos/cursive" }
json = "0.12.4"
